NVIDIA/go-nvml

go.mod

This change adds a `go.mod` file to the repository created by running `go mod init`. This allows for the package to be used as a module (and consumed as such).
It also means that the package does not need to be in the GOPATH to develop.
Before:
```
$ make test
cd /home/elezar/src/go-nvml/pkg/nvml; \
go test -v .; \
cd -> /dev/null
init.go:19:2: cannot find package "github.com/NVIDIA/go-nvml/pkg/dl" in any of:
/usr/local/go/src/github.com/NVIDIA/go-nvml/pkg/dl (from $GOROOT)
/home/elezar/go/src/github.com/NVIDIA/go-nvml/pkg/dl (from $GOPATH)
```
After
```
$ make test
cd /home/elezar/src/go-nvml/pkg/nvml; \
go test -v .; \
cd -> /dev/null
=== RUN   TestInit
--- FAIL: TestInit (0.00s)
panic: error opening libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or …
```

Run go mod init to set up go-nvml as a Go module

---

Dockerfile
Makefile
README.md

This change adds a basic Dockerfile that includes the c-for-go
dependency to allow the generation of bindings without installing
this dependency.
A generic make target `docker-%` is added to run any of the recognised
make targets in the container.
```bash
$ make \t\t
all                    clean                  docker-all             docker-clean           docker-test            image                  test-bindings
bindings               clean-bindings         docker-bindings        docker-clean-bindings  docker-test-bindings   test
```
Note that this pins:
* The GO version to 1.14.4
* The c-for-go commit to 8eeee8c3b71f9c3c90c4a73db54ed08b0bba971d
To ensure that this does not introduce any changes when generating
the bindings.

Add docker build

---

gen/nvml/init.go
gen/nvml/return.go

```
Author: Kevin Klues <kklues@nvidia.com>
Date:   Tue Jan 19 16:28:58 2021 +0000
Fix error check in call to set versioned API calls
Previously, it was checking them against nvml.Return types (which was
wrong on many levels). It only happened wot work on my tests because I
had a machine with the latest API calls for everything.
Signed-off-by: Kevin Klues <kklues@nvidia.com>
```
```
Author: Kevin Klues <kklues@nvidia.com>
Date:   Tue Jan 19 16:27:06 2021 +0000
Add Value() call to nvml.Return type
Not necessary when using the package API directly, but helps with
mocking out the Return type in higher level libraries and then having
them be able to easily swap in the package based implementation at a
later time.
Signed-off-by: Kevin Klues <kklues@nvidia.com>
```

Update Return type with an exrtra API call and fix bug in versioned APIs

---

gen/nvml/device.go

The initial call to nvmlDeviceGetProcessUtilization to determine the number
of samples for which a buffer must be allocated returns ERROR_INSUFFICIENT_SIZE
and not SUCCESS.
Addresses #11 
Signed-off-by: Evan Lezar <elezar@nvidia.com>

Check for ERROR_INSUFFICIENT_SIZE for GetProcessUtilization

---

Makefile
examples/compute-processes/main.go
examples/devices/main.go
gen/nvml/device.go
gen/nvml/vgpu.go
pkg/nvml/device.go
pkg/nvml/vgpu.go

This changes fixes errors introduced in the update to NVML 11.2 and adds examples to allow these errors to be detected earlier.

Fix errors from 11.2 update and add examples

---

gen/nvml/device.go
gen/nvml/init.go
pkg/nvml/device.go
pkg/nvml/init.go

The definition of `struct nvmlProcessInfo_st` has introduce two new fields `gpuInstanceId` and `computeInstanceId` in newer NVIDIA drivers (CUDA 11.x). And this changes will break the backward compatibility for old NVIDIA drivers (CUDA 10.x).
This PR fixes issue #21 for `nvmlDeviceGetComputeRunningProcesses` `nvmlDeviceGetGraphicsRunningProcesses` on CUDA 10.x caused by the data structure size change. It simply calls the v1 version function (feed with v1 data structure) and convert the results into v2 ones on CUDA 10.x. And for CUDA 11.x, call the v2 version directly.
There is another solution (PR #22) that calls the v1 version (but feed with v2 data structure) and correct the results with some adjustments on CUDA 10.x. As commented in …

Fix GetComputeRunningProcesses on CUDA 10.x

---

gen/nvml/device.go
pkg/nvml/device.go

Without this fix, the following code would produce an error:
uuid := "GPU-3eb87630-93d5-b2b6-b8ff-9b359caf4ee2"
device, ret = nvml.DeviceGetHandleByUUID(uuid)
if ret != nvml.SUCCESS {
fmt.Printf("uuid nvml.DeviceGetHandleByUUID(%v): %v\n", uuid, nvml.ErrorString(ret))
os.Exit(1)
}
Even if the UUID pointed to by the hard-coded string was valid. This is due to
the fact that the generated c-for-go code assumes that all go-string inputs are
actually backed by a valid null-terminated C-string under the hood. This is
true when we pull the string from go-nvml, e.g. via `device.GetUUID()`, but not
necessarily when we hard code the string ourselves (or store it to a file and
then try and use it to retrieve a device handle later).
The fix is to ensure that all go-string inputs are actually …

Fix a bug with handling non-null-terminated strings as input

---

pkg/dl/dl.go
pkg/dl/dl_linux_test.go

This PR is intended to make `dl` calls thread-safe. Problem might occur if, for example, `dlopen()` and `dlerror()` were run in different goroutines and there was an error which happened after `dlopen()` but was ignored.
To fix this behaviour, each dl call (`dlopen()`, `dlsym()`, `dlclose()`) runs in the same thread with its `dlerror()` call. This is done using `runtime.LockOSThread()` wrapper around those calls.

Make dl package thread-safe

---

.github/dependabot.yml

This adds a basic dependabot config that update go modules and github actions.

Add basic dependabot

---

gen/nvml/nvml.yml
pkg/nvml/const.go
pkg/nvml/nvml.go

Closes #36 
Investigation on the Go side https://github.com/golang/go/issues/63264
When built with `go1.21.x`, `go-nvml` panics. This is due to a change in how `go tool link` executes the external linker. Previously, `-rdynamic` was always passed to the external linker, however this was changed to only happen in certain circumstances, such as when linking to previously built CGO shared objects, or when the flag to export specific dynamic symbols isn't supported. The justification for the change is in https://github.com/golang/go/issues/53579.
The resolution I propose for `go-nvml` is to pass the `--export-dynamic` flag into `LDFLAGS` explicitly. This LDFLAG is required because if it is not present, the symbols from `nvml.h` are not added to the PLT, meaning each call to a symbol from …

gen/nvml: add `--export-dynamic` linker flag

---

Makefile

This change bumps the golang version used for generating bindings in containers.

Bump golang tooling version

---

gen/nvml/lib.go
pkg/nvml/lib.go

This change adds a top-level LookupSymbol function. This replaces the need to explicitly open a library locally and check the symbols there in clients of these bindings.
Note that this API is considered experimental.

Add top-level function to lookup symbols

---

gen/nvml/api.go
gen/nvml/init.go
gen/nvml/lib.go
gen/nvml/lib_test.go
gen/nvml/nvml_test.go
pkg/nvml/api.go
pkg/nvml/init.go
pkg/nvml/lib.go
pkg/nvml/lib_test.go
pkg/nvml/nvml_test.go

These changes add a basic API for allowing the path to `libnvidia-ml.so.1` to be set.
This can be used in environments where the path to the library can be determined programatically but not reliably added to the `LD_LIBRARY_PATH` before program startup, for example.
This builds on the changes from #86

Allow path to libnvidia-ml.so.1 to be specified

---

gen/nvml/return.go
pkg/nvml/return.go

This change adds a fallback ErrorString function that is used when the nvmlErrorString function cannot be resolved. For example, when the library is not loaded.
Closes #82

Add fallback ErrorString function

---

pkg/nvml/init.go

This change removes the panic from the shutdown code. Instead an ERROR_UNKNOWN is returned. This does cause the source of the error to be lost, but this can be addressed in a follow-up.
This replaces #70

Return ERROR_UNKNOWN instead of panicing

---

pkg/nvml/init.go
pkg/nvml/lib.go

Without this change, go-nvlib is broken, when looking up symbol names, for example. Also, no v2 or v3 symbols are loaded as expected which breaks, for example, `GetGpuInstancePossiblePlacements()` for the extended media types.

Fix bug with wrong instance of lib being called for load/close

---

pkg/nvml/device.go
pkg/nvml/device_test.go
pkg/nvml/gpm.go
pkg/nvml/vgpu.go

This was done in go-nvlib in https://github.com/NVIDIA/go-nvlib/pull/17 but not included when we implemented the interfaces here.
Without the explict `nvmlDevice` conversion we see:
```
=== RUN   TestGetTopologyCommonAncestor
--- FAIL: TestGetTopologyCommonAncestor (0.00s)
panic: interface conversion: nvml.Device is nvml.wrappedDevice, not nvml.nvmlDevice [recovered]
panic: interface conversion: nvml.Device is nvml.wrappedDevice, not nvml.nvmlDevice
goroutine 19 [running]:
testing.tRunner.func1.2({0x1030fc500, 0xc0000b10b0})
/usr/local/Cellar/go/1.22.2/libexec/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
/usr/local/Cellar/go/1.22.2/libexec/src/testing/testing.go:1634 +0x377
panic({0x1030fc500?, 0xc0000b10b0?})
/usr/local/Cellar/go/1.22.2/libexec/src/runtime/panic.go:770 …
```

Add internal method to get device handle

---

examples/gpm-metrics/main.go
pkg/nvml/gpm.go
pkg/nvml/gpm_test.go

These changes ensure that the collected GPM metrics are transferred to the original data structure passed to `GpmMetricsGet`.
Closes #121

Fix missing GPM metrics

---

Makefile

An example of running this now looks like:
```console
$ make update-nvml-h
Found 9 NVML headers:
No.  Version   Upload Time
1  12.5.39   2024-05-21T16:33:04
2  12.4.127  2024-04-03T20:31:07
3  12.4.99   2024-03-05T17:03:22
4  12.3.101  2023-11-16T22:01:02
5  12.3.52   2023-10-19T15:56:27
6  12.2.140  2023-08-29T15:40:51
7  12.2.128  2023-07-31T15:43:39
8  12.2.81   2023-06-28T15:36:05
9  12.1.105  2023-04-19T15:31:00
Pick an NVML header to update ([1]-9): 1
NVML version: 12.5.39
Updating nvml.h to 12.5.39 from https://gitlab.com/nvidia/headers/cuda-individual/nvml_dev/-/raw/v12.5.39/nvml.h ...
--2024-05-24 20:46:21--  https://gitlab.com/nvidia/headers/cuda-individual/nvml_dev/-/raw/v12.5.39/nvml.h
Resolving gitlab.com (gitlab.com)... 172.65.251.78, 2606:4700:90:0:f22e:fbec:5bed:a9b9 …
```

Update source for NVML header downloads to NVIDIA owned repo

---

.github/workflows/golang.yml
.golangci.yaml
pkg/nvml/device.go
pkg/nvml/gpm.go
pkg/nvml/mock/dgxa100/dgxa100.go

The following lint issues have been fixed
```
^
pkg/nvml/mock/dgxa100/dgxa100.go:22:1: File is not properly formatted (goimports)
^
pkg/nvml/mock/dgxa100/dgxa100.go:111:23: composites: github.com/NVIDIA/go-nvml/pkg/nvml.Memory struct literal uses unkeyed fields (govet)
MemoryInfo:         nvml.Memory{42949672960, 0, 0},
^
gen/nvml/generateapi.go:106:2: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
fmt.Fprintf(writer, header)
^
gen/nvml/generateapi.go:115:4: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
fmt.Fprintf(writer, comment)
^
gen/nvml/generateapi.go:130:3: SA1006: printf-style function with dynamic format …
```

migrate to golangci-lint v2

---

.github/workflows/golang.yml
Makefile
gen/nvml/generateapi.go
pkg/nvml/device.go
pkg/nvml/event_set.go

The following lint errors have been fixed as part of this PR changeset 
```
pkg/nvml/device.go:71:26: func GpuInstanceInfo.convert is unused (unused)
func (g GpuInstanceInfo) convert() nvmlGpuInstanceInfo {
^
pkg/nvml/device.go:100:30: func ComputeInstanceInfo.convert is unused (unused)
func (c ComputeInstanceInfo) convert() nvmlComputeInstanceInfo {
^
pkg/nvml/event_set.go:26:20: func EventData.convert is unused (unused)
func (e EventData) convert() nvmlEventData {
gen/nvml/generateapi.go:130:3: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
fmt.Fprintf(writer, comment)
^
gen/nvml/generateapi.go:137:3: SA1006: printf-style function with dynamic format string and no further arguments should use …
```

[CI] re-enable the check stage

---

pkg/nvml/device.go
pkg/nvml/mock/device.go
pkg/nvml/mock/interface.go
pkg/nvml/zz_generated.api.go

This is a BREAKING CHANGE, but one that is necessary, because the API is unusable in its current form. In the C API, the input struct us used to pass _both_ input _and_ output. In our original implementation we didn't take this struct as input, so there was no way to get this input passed into the function. The API has now been updated to correct this.
One option could have been to just add the single input field as an input to the API call on its own, but this is not scalable in cases where one my add more input fields to the struct in the future.
In the end, (even though this goes against our other wrapper API calls), we decided it was best to just pass the whole struct and assume its usage as both input and output just like the C API.
We plan to revisit how to more comprehensively …

Update DeviceGetconfComputeGpuAttestationReport to take struct as input
